name: CI

on: push

jobs:
  test:
    name: ${{ matrix.lisp }} on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin]

    steps:
      - uses: actions/checkout@v4
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Rove
        run: ros install rove
      - name: Run tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove lack.asd
